//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internetbursa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilcelerr
    {
        public int ilce_id { get; set; }
        public string ilce_ad { get; set; }
        public string link { get; set; }
    }
}
