//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internetbursa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public int kullanici_id { get; set; }
        public string ad_soyad { get; set; }
        public string email { get; set; }
        public string sifre { get; set; }
        public Nullable<int> rol { get; set; }
    
        public virtual roller roller { get; set; }
    }
}
