//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internetbursa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class resimlerr
    {
        public int resimid { get; set; }
        public string resim_url { get; set; }
        public byte[] resim { get; set; }
    }
}
