//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace internetbursa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turistikyerler
    {
        public int turistik_yer_id { get; set; }
        public string yer_ad { get; set; }
        public string aciklama { get; set; }
        public string konum { get; set; }
    }
}
